{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sentry-operator.serviceAccountName" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "sentry-operator.name" . }}
    heritage: {{ .Release.Service }}
    release: "{{ .Release.Name }}"
imagePullSecrets: {{ toYaml .Values.image.pullSecrets | nindent 2 }}
{{- end }}